services:
  # MongoDB 服务
  mongodb:
    image: mongo:6.0
    container_name: waf-demo-mongodb
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example # 请替换为您的实际密码
      # 可选：指定初始数据库名称
      # MONGO_INITDB_DATABASE: waf_db
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb # 添加配置数据卷
    ports:
      - "27018:27017"
    networks:
      - waf-network
    # 可选：添加命令行参数
    # command: --wiredTigerCacheSizeGB 1.5

  # RuiQi WAF 服务（统一使用小写命名）
  ruiqi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ruiqi-waf # 容器名小写
    restart: always
    depends_on:
      - mongodb
    environment:
      DB_URI: mongodb://192.168.31.55:27018 # 请替换为您的实际密码
      JWT_SECRET: ffffffffffffffffffffffffffffff
      IS_PRODUCTION: "false"
      VITE_API_BASE_URL: http://localhost:2333/api/v1
    ports:
      - "2333:2333"
      - "8080:8080"
      - "9443:9443"
      - "443:443"
      - "80:80"
      - "8404:8404"
      - "8090-8099:8090-8099"
    volumes:
#      - ruiqi_data:/app/data
      - ./data:/app/data
    networks:
      - waf-network

# 定义持久化卷
volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  ruiqi_data:
    driver: local

# 定义网络
networks:
  waf-network:
    driver: bridge
