name: 🐞 Bug Report

description: Report a bug to help improve RuiQi WAF

title: "[Bug] <title>"
labels: [bug, needs-triage]
assignees: "HUAHUAI23"

body:
  - type: checkboxes
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following items before submitting
      options:
        - label: I have searched existing issues and confirmed this is not a duplicate
          required: true
        - label: I have read the documentation and this issue is not covered
          required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Type
      description: How are you running RuiQi WAF?
      options:
        - Docker Compose
        - Standalone Docker
        - Local Development
        - Sealos Template
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is experiencing the issue?
      options:
        - Frontend UI
        - Backend API
        - HAProxy Integration
        - Coraza WAF Engine
        - MicroEngine
        - Geographic Analysis
        - Rate Limiting
        - Authentication
        - Database
        - Docker Build
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Bug Description
      description: Clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Configure '...'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment Information
      description: Please provide your environment details
      placeholder: |
        - OS: (e.g., Ubuntu 22.04, Windows 11, macOS 14)
        - Go Version: (e.g., 1.24.1)
        - Node.js Version: (if applicable)
        - HAProxy Version: (e.g., 3.0)
        - MongoDB Version: (e.g., 6.0)
        - Browser: (if frontend issue)
        - Docker Version: (if using Docker)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Logs and Error Messages
      description: |
        Relevant logs, error messages, or stack traces
        
        Tip: You can attach files by clicking this area and dragging files in
      placeholder: |
        Please paste logs here...
        
        For WAF-related issues, please include:
        - HAProxy logs
        - Coraza SPOA logs
        - Application logs

  - type: textarea
    attributes:
      label: WAF Configuration
      description: If this is related to WAF rules or configuration, please provide relevant details
      placeholder: |
        - Rule sets being used
        - Custom rules (if any)
        - HAProxy configuration snippets
        - Traffic patterns

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Any other context about the problem
        
        Screenshots, network traces, or other relevant information
