name: ✨ Feature Request

description: Suggest a feature or idea for RuiQi WAF

title: "[Feature] <title>"
labels: [enhancement, needs-triage]
assignees: "HUAHUAI23"

body:
  - type: checkboxes
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following items before submitting
      options:
        - label: I have searched existing issues and confirmed this feature request is not a duplicate
          required: true
        - label: I have checked the roadmap and this feature is not already planned
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which category does this feature belong to?
      options:
        - Security Enhancement
        - Performance Optimization
        - User Interface Improvement
        - API Enhancement
        - Monitoring & Analytics
        - Rule Management
        - Configuration Management
        - Integration
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my adoption
    validations:
      required: true

  - type: textarea
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you would like to see
      placeholder: Describe the feature you want...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point are you experiencing?
      placeholder: |
        Current situation:
        - What is the current behavior?
        - What limitations are you facing?
        - How is this affecting your workflow?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Detailed description of your proposed solution:
        - How should it work?
        - What should the user interface look like?
        - What configuration options should be available?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        Example use cases:
        1. When configuring WAF rules for...
        2. When monitoring traffic from...
        3. When integrating with...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        Alternative approaches you've considered:
        - Current workarounds you're using
        - Other tools or methods you've tried
        - Why these alternatives are not sufficient

  - type: textarea
    attributes:
      label: Technical Considerations
      description: Any technical details, constraints, or implementation ideas
      placeholder: |
        Technical aspects to consider:
        - Performance implications
        - Security considerations
        - Compatibility requirements
        - Integration points

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Any other context, screenshots, mockups, or references
        
        You can attach images or files by clicking this area and dragging them in
