name: ✨ 功能请求

description: 为 RuiQi WAF 建议新功能或想法

title: "[功能] <标题>"
labels: [enhancement, needs-triage]
assignees: "HUAHUAI23"

body:
  - type: checkboxes
    attributes:
      label: 提交前检查清单
      description: 请在提交前确认以下项目
      options:
        - label: 我已搜索现有问题并确认此功能请求不是重复的
          required: true
        - label: 我已检查路线图，此功能尚未计划
          required: true

  - type: dropdown
    id: category
    attributes:
      label: 功能类别
      description: 此功能属于哪个类别？
      options:
        - 安全增强
        - 性能优化
        - 用户界面改进
        - API 增强
        - 监控和分析
        - 规则管理
        - 配置管理
        - 集成
        - 文档
        - 其他
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 此功能对您有多重要？
      options:
        - 低 - 有了更好
        - 中 - 会很有帮助
        - 高 - 对我的用例很重要
        - 关键 - 阻碍我的采用
    validations:
      required: true

  - type: textarea
    attributes:
      label: 功能描述
      description: 清晰简洁地描述您希望看到的功能
      placeholder: 描述您想要的功能...
    validations:
      required: true

  - type: textarea
    attributes:
      label: 问题陈述
      description: 此功能解决什么问题？您遇到了什么痛点？
      placeholder: |
        当前情况：
        - 当前行为是什么？
        - 您面临什么限制？
        - 这如何影响您的工作流程？
    validations:
      required: true

  - type: textarea
    attributes:
      label: 建议解决方案
      description: 您希望此功能如何工作？
      placeholder: |
        您建议解决方案的详细描述：
        - 它应该如何工作？
        - 用户界面应该是什么样的？
        - 应该有哪些配置选项？
    validations:
      required: true

  - type: textarea
    attributes:
      label: 使用场景
      description: 描述此功能有用的具体场景
      placeholder: |
        示例使用场景：
        1. 当为...配置 WAF 规则时
        2. 当监控来自...的流量时
        3. 当与...集成时
    validations:
      required: true

  - type: textarea
    attributes:
      label: 替代方案
      description: 您是否考虑过任何替代解决方案或变通方法？
      placeholder: |
        您考虑过的替代方法：
        - 您目前使用的变通方法
        - 您尝试过的其他工具或方法
        - 为什么这些替代方案不够充分

  - type: textarea
    attributes:
      label: 技术考虑
      description: 任何技术细节、约束或实现想法
      placeholder: |
        需要考虑的技术方面：
        - 性能影响
        - 安全考虑
        - 兼容性要求
        - 集成点

  - type: textarea
    attributes:
      label: 其他上下文
      description: |
        任何其他上下文、截图、模型或参考资料
        
        您可以点击此区域并拖拽文件来附加图片或文件 